### ISSUE TITLE
4k

### ISSUE THREAD

**Issue by JouBqa** [raphipod/pop-wallpaper#1]
Any change of getting the dynamic pop wallpapers in 3840 x 2160?

**Comment by raphipod** [comment]
Hey @JouBqa, thanks for asking!

IIRC, the original pictures posted on Reddit were in 4k resolution, but I had to downscale them to 1080p due to space constraints on GitHub.

Edit: Just found them, they all are in 4096x2160, a downscaling tool could help getting them to your desired 4k 16:9 resolution!
Here you have a link to the thread I've taken them from: https://www.reddit.com/r/pop_os/comments/n62iid/a_set_of_dynamic_wallpapers_made_by_me/

Hope I could help!

**Comment by raphipod** [comment]
As I don't hear any feedback, I assume this issue was resolved! Best regards!

**Comment by JouBqa** [comment]
They are in webmp I beed png or jgp?

**Comment by raphipod** [comment]
On Chrome, if you right-click the pics on the Reddit page, they are shown in JPG format.
Below, I've got them in the original full resolution! Just right click on them, and save them.

![9q288cf0ngx61](https://user-images.githubusercontent.com/56308821/120101907-d2994c00-c148-11eb-815e-58616abe052c.jpg)
![jgz272f0ngx61](https://user-images.githubusercontent.com/56308821/120101913-d4fba600-c148-11eb-97dc-2549745e71ed.jpg)
![zytgn1f0ngx61](https://user-images.githubusercontent.com/56308821/120101915-d6c56980-c148-11eb-86e9-1e0c8232a3d1.jpg)
![night](https://user-images.githubusercontent.com/56308821/120101924-e644b280-c148-11eb-8e77-dfb3440525e3.png)

**Comment by JouBqa** [comment]
Thanks

**Comment by raphipod** [comment]
Great that we could sort this out!
